.\" Manpage for Welcome2L
.\" https://github.com/voyageur/welcome2l
.TH Welcome2L 1 "Welcome2L Version 3.05" "20/Apr/17" "Welcome2L User's Manual"
.SH NAME
Welcome2L - Linux ANSI boot logo
.SH SYNOPSIS
.B Welcome2L
[ \fI\-scr\fR xx ] [ \fI\-getty\fR ] [ \fI\-gettps\fR ] [ \fI\-msg\fR message ] [ \fI\-cpu\fR name ] [ \fI-scrrand\fR ] [ \fI-xmas\fR ] [ \fI\-xmasauto\fR ] [ \fI\-lcol\fR xx ] [ \fI\-nolf\fR ] [ \fI\-private\fR ] [\fI\-notime\fR \]
.SH DESCRIPTION
.B Welcome2L
is a little program that may run at login time to produce a BBS like ANSI login
logo. It's very similar to Linux_Logo. But where Linux_Logo intends to be
portable, Welcome2L intends to produce the best looking ANSI screens by making
full usage of PC graphic characters. Therefore an architecture able to display
those characters (i386, Alpha with TGA adapter, \&... ) is required to use it.
And, even if it will work on larger screens, it will only produce 80 column
ANSI screens. 
.SH OPTIONS
.TP
.I "-getty"
will display more accurate information when launched at boot time.
.TP
.I "-gettps"
Like
.I "-getty"
but works with 
.I gettyps(8)
program.
.TP
.I "-nolf"
will not add an empty line to the ansi screen produced.
.TP
.I "-msg" message
will show the message given as the distribution info.
.TP
.I "-cpu"name
will show the name given as the CPU name.
.TP
.I "-scr xx"
will display screen number xx. 
.TP
.I "\-scrrand"
will display a random screen. 
.TP
.I "-xmas"
will display an Xmas screen.
.TP
.I "-xmasauto"
will automatically display an Xmas screen in December and January.
.TP
.I "-lcol" xx
will change the prompt color to the color number xx. Use the help command to
see what number is attributed to a color.
.TP
.I "-private"
Display an "Unauthorized access is prohibited" line at the bottom 
of the ANSI screen.
.TP
.I "-notime"
When displaying date information, do not display time.
.TP
.I "-noblink"
Turn blinking off. Useful with
.I -xmas
or
.I -xmasauto
on framebuffer devices, which do not support blinking.
.TP
.I "-help"
will display usage information.
.SH EXAMPLE
\&/usr/bin/Welcome2L -getty -msg "Gentoo Linux" -lcol 14 -scr 02
.SH RESTRICTIONS
Welcome2L is not intended to run in a xterm.
.SH "CAVEAT"
Because "A 'welcome' page has been proven to be an invitation to come your
system, thus making it legal to hack into your box.", you may want to use the
"\-private" arg when running Welcome2L to display an "Unauthorized access is
prohibited" line at the bottom of the ANSI screen. 
.SH "LICENSE"
.B Welcome2L
is released under the terms of the GNU GPL.
.SH "AUTHORS"
Jean-Marc Jacquet <jm@littleigloo.org>
