=head1 NAME

Welcome2l - Linux ANSI boot logo.


=head1 SYNOPSIS

B<Welcome2L> [ B<-scr> ] [ B<-getty> ] [ B<-msg> ] [ B<-cpu> ] [ B<-lcol> ]  [ B<-nolf> ] [ B<-private> ]


=head1 DESCRIPTION

B<Welcome2L> is a little program that may run at login time to produce a BBS
like ANSI login logo. It's very similar to Linux_Logo. But where Linux_Logo
intends to be portable, Welcome2L intends to produce the best looking
ANSI screens by making full usage of PC graphic characters. Therefore
an architecture able to display those characters (i386, Alpha with TGA adapter,
... ) is required to use it. And, even if it will work on larger screens,
it will only produce 80 column ANSI screens. 



=head1 OPTIONS

=over 8

=item B<-getty>

Will display more accurate information when launched at boot time.


=item B<-nolf>

Will not add an empty line to the ansi screen produced.


=item B<-msg>

-msg"text of message" will show the message given as the distribution info.

=item B<-cpu>

-cpu"name" will show the  name given as the CPU name.


=item B<-scr>xx

Will display screen number xx. 


=item B<-scrrand>

Will display a random screen. 


=item B<-lcol>xx

Will change the prompt color to the color number xx. Type Welcome2L -help to see
what number is attributed to a color.


=item B<-private>

Display an "Unauthorized access is prohibited" line at the bottom 
of the ANSI screen

=item B<-help>

Will display usage information. 

=back


=head1 EXAMPLE

./Welcome2L -getty -msg"Gentoo Linux" -lcol14


=head1 RESTRICTIONS

Welcome2L is not intended to run in a xterm.

=head1 CAVEAT

Because "A 'welcome' page has been proven to be an invitation 
to come your system, thus making it legal to hack into your box." 
you may want to use the "-private" arg when running Welcome2L
to display an "Unauthorized access is prohibited" line at the bottom 
of the ANSI screen. 


=head1 COPYRIGHT

B<Welcome2L Copyright (C)1998-1999 Little Igloo Org> is freely distributable 
under the B<GNU Public License>, a copy of which you should have received 
with this software (in a file called F<COPYING>).


=head1 AVAILABILITY

You can get the last Welcome2L version, sources, binaries distribution
or RedHat Packages, at : F<http://www.LittleIgloo.org>


=head1 AUTHOR

Jean-Marc Jacquet <jm@littleigloo.org>
